const dummyData = {
    description:
        "Software engineers create web applications, mobile apps, robots, operating systems, and network systems. They develop software solutions that meet their companies' needs and expectations. Depending on the type of company they work for, software engineers will create original code for software and applications. They also build reusable code for future use.",
    do: [
        "Designing and maintaining software systems",
        "Evaluating and testing new software programs",
        "Optimizing software for speed and scalability",
        "Writing and testing code",
        "Consulting with clients, engineers, security specialists, and other stakeholders",
        "Presenting new features to stakeholders and internal customers",
    ],
    skills: [
        "Problem-solving skills",
        "Attention to detail",
        "Teamwork",
        "Independent learner",
        "Work well under pressure",
    ],
    how: [
        {
            title: "Gain academic qualification or certificates",
            text: "Acquire formal education or industry-recognized certifications to enhance your technical skills.",
            icon: "certificate",
            showCourse: true,
            showM1Course: false,
            showJob: false,
        },
        {
            title: "Learn a language, framework or tech stack",
            text: "Build a strong foundation in your chosen programming languages or technology stacks. ",
            icon: "skills",
            showCourse: false,
            showM1Course: true,
            showJob: false,
        },
        {
            title: "Grasp data structures and algorithms",
            text: "Strengthen your problem-solving skills by mastering essential data structures and algorithms.",
            icon: "database",
            showCourse: false,
            showM1Course: false,
            showJob: false,
        },
        {
            title: "Create projects and grow your portfolio",
            text: "Build real-world projects to showcase your skills and expand your professional portfolio.",
            icon: "file",
            showCourse: false,
            showM1Course: false,
            showJob: false,
        },
        {
            title: "Explore internship opportunities",
            text: "Gain hands-on experience and valuable insights through targeted internship programmes.",
            icon: "building",
            showCourse: false,
            showM1Course: false,
            showJob: false,
        },
        {
            title: "Start applying for work!",
            text: "Begin your professional journey by applying for roles that align with your skills and aspirations.",
            icon: "briefcase",
            showCourse: false,
            showM1Course: false,
            showJob: true,
        },
    ],
};

export const db_roles = [
    {
        title: "Software Engineer",
        slug: "se",
        paraTitle: "software engineer",
        featured: true,
        description:
            "Software engineers design, develop, test, and maintain software systems. This role is vital as software is integral to modern society, driving everything from daily communications to complex scientific research. Effective software engineering is essential for innovation and efficiency in various sectors.",
        do: [
            "Develop and maintain software systems",
            "Write, test, and debug code",
            "Collaborate with product and design teams",
            "Update and integrate software components",
            "Review code and integrate user feedback",
        ],
        skills: [
            {
                title: "Analytical thinking",
                slug: "calc",
            },
            {
                title: "Problem-solving ability",
                slug: "problem",
            },
            {
                title: "Team collaboration",
                slug: "teamwork",
            },
            {
                title: "Independent learner",
                slug: "learn",
            },
            {
                title: "Work well under pressure",
                slug: "time",
            },
        ],
        how: [
            {
                title: "Gain academic qualification or certificates",
                text: "Acquire formal education or industry-recognized certifications to enhance your technical skills.",
                icon: "certificate",
                showCourse: true,
                showM1Course: false,
                showJob: false,
            },
            {
                title: "Learn a language, framework or tech stack",
                text: "Build a strong foundation in your chosen programming languages or technology stacks. ",
                icon: "skills",
                showCourse: false,
                showM1Course: true,
                showJob: false,
            },
            {
                title: "Grasp statistical and data visualisation skills",
                text: "Strengthen your problem-solving skills by mastering essential data structures and algorithms.",
                icon: "database",
                showCourse: false,
                showM1Course: false,
                showJob: false,
            },
            {
                title: "Create projects and grow your portfolio",
                text: "Build real-world projects to showcase your skills and expand your professional portfolio.",
                icon: "file",
                showCourse: false,
                showM1Course: false,
                showJob: false,
            },
            {
                title: "Explore internship opportunities",
                text: "Gain hands-on experience and valuable insights through targeted internship programmes.",
                icon: "building",
                showCourse: false,
                showM1Course: false,
                showJob: false,
            },
            {
                title: "Start applying for work!",
                text: "Begin your professional journey by applying for roles that align with your skills and aspirations.",
                icon: "briefcase",
                showCourse: false,
                showM1Course: false,
                showJob: true,
            },
        ],
    },
    {
        title: "Frontend Development",
        slug: "frontend",
        paraTitle: "frontend developer",
        featured: false,
        ...dummyData,
    },
    {
        title: "Backend Development",
        slug: "backend",
        paraTitle: "backend developer",
        featured: false,
        ...dummyData,
    },
    {
        title: "Data Science",
        slug: "data",
        paraTitle: "data scientist",
        featured: true,
        description:
            "Data scientists are experts who specialize in analyzing and interpreting complex digital data, such as the usage statistics of a website, especially in order to assist a business in its decision-making. The role is crucial as data-driven insights are increasingly becoming central to business strategies, enhancing operational efficiency and competitive edge in various industries.",
        do: [
            "Collect, process, and clean data from various sources",
            "Use statistical tools to interpret data and detect trends",
            "Develop predictive models and machine-learning algorithms",
            "Collaborate with business and IT teams",
            "Visualize data for stakeholder presentations",
        ],
        skills: [
            {
                title: "Critical thinking",
                slug: "problem",
            },
            {
                title: "Attention to detail",
                slug: "detail",
            },
            {
                title: "Effective communication",
                slug: "teamwork",
            },
            {
                title: "Curiosity & creativity",
                slug: "creative",
            },
            {
                title: "Adaptability",
                slug: "adapt",
            },
        ],
        how: [
            {
                title: "Gain academic qualification or certificates",
                text: "Earn a certificate or degree in Statistics, Computer Science, or related field",
                icon: "certificate",
                showCourse: true,
                showM1Course: false,
                showJob: false,
            },
            {
                title: "Learn a language, framework or tech stack",
                text: "Gain proficiency in analytics and programming languages like Python or R",
                icon: "skills",
                showCourse: false,
                showM1Course: true,
                showJob: false,
            },
            {
                title: "Explore internship opportunities",
                text: "Participate in internships or entry-level positions to gain experience",
                icon: "building",
                showCourse: false,
                showM1Course: false,
                showJob: false,
            },
            {
                title: "Create projects and grow your portfolio",
                text: "Develop a portfolio of relevant projects",
                icon: "file",
                showCourse: false,
                showM1Course: false,
                showJob: false,
            },
            {
                title: "Start applying for work!",
                text: "Begin your professional journey by applying for roles that align with your skills and aspirations.",
                icon: "briefcase",
                showCourse: false,
                showM1Course: false,
                showJob: true,
            },
        ],
    },
    {
        title: "Digital Marketer",
        slug: "dm",
        paraTitle: "digital marketer",
        featured: true,
        description:
            "Digital marketers strategize and implement marketing campaigns across digital platforms to build brand awareness, generate leads, and drive conversions. This role is crucial in today’s digital-first world, as effective digital marketing strategies are essential for businesses to reach and engage their target audience effectively.",
        do: [
            "Develop and execute digital marketing campaigns",
            "Analyze data to identify trends and insights",
            "Manage social media platforms and content",
            "Optimize website and social media content for SEO",
            "Monitor and report on campaign performance",
        ],
        skills: [
            {
                title: "Strategic thinking",
                slug: "problem",
            },
            {
                title: "Creativity and innovation",
                slug: "creative",
            },
            {
                title: "Data analysis proficiency",
                slug: "calc",
            },
            {
                title: "Strong communication skills",
                slug: "comm",
            },
            {
                title: "Adaptability to trends",
                slug: "adapt",
            },
        ],
        how: [
            {
                title: "Gain academic qualification or certificates",
                text: "Earn a certificate or degree in marketing, communications, or related field to build foundational knowledge.",
                icon: "certificate",
                showCourse: true,
                showM1Course: false,
                showJob: false,
            },
            {
                title: "Learn a language, framework or tech stack",
                text: "Develop a strong understanding of digital marketing tools and platforms, such as Google Analytics, AdWords, and social media management software.",
                icon: "skills",
                showCourse: false,
                showM1Course: true,
                showJob: false,
            },
            {
                title: "Keep your skills up-to-date",
                text: "Stay current with digital marketing trends and changes in SEO, social media, and email marketing tactics.",
                icon: "database",
                showCourse: false,
                showM1Course: false,
                showJob: false,
            },
            {
                title: "Explore internship opportunities",
                text: "Gain practical experience through internships or entry-level positions in marketing firms or departments.",
                icon: "building",
                showCourse: false,
                showM1Course: false,
                showJob: false,
            },
            {
                title: "Start applying for work!",
                text: "Begin your professional journey by applying for roles that align with your skills and aspirations.",
                icon: "briefcase",
                showCourse: false,
                showM1Course: false,
                showJob: true,
            },
        ],
    },
    {
        title: "Cybersecurity",
        slug: "cs",
        paraTitle: "cybersecurity engineer",
        featured: true,
        description:
            "Cybersecurity professionals protect systems, networks, and data from digital attacks. This role is critical as it ensures the integrity, confidentiality, and availability of information, which is increasingly vital in today’s data-driven society where digital threats are constantly evolving.",
        do: [
            "Monitor systems for security breaches",
            "Implement security measures and protocols",
            "Conduct risk assessments and audits",
            "Respond to security incidents and breaches",
            "Stay updated with the latest security threats and countermeasures",
        ],
        skills: [
            {
                title: "Analytical problem-solving",
                slug: "problem",
            },
            {
                title: "Attention to detail",
                slug: "detail",
            },
            {
                title: "Strong ethical standards",
                slug: "adapt",
            },
            {
                title: "Effective communication",
                slug: "comm",
            },
            {
                title: "Adaptability under pressure",
                slug: "time",
            },
        ],
        how: [
            {
                title: "Gain academic qualification or certificates",
                text: "Obtain a certification in degree in computer science, cybersecurity, or a related field to gain fundamental IT security knowledge.",
                icon: "certificate",
                showCourse: true,
                showM1Course: false,
                showJob: false,
            },
            {
                title: "Expand your knowledge and skills",
                text: "Pursue relevant beginner or advanced certifications like CompTIA Security+, CEH (Certified Ethical Hacker), or CISSP (Certified Information Systems Security Professional) to enhance your skills and credibility.",
                icon: "skills",
                showCourse: false,
                showM1Course: true,
                showJob: false,
            },
            {
                title: "Explore internship opportunities",
                text: "Gain experience through internships or entry-level positions in IT or security to understand real-world cybersecurity challenges.",
                icon: "building",
                showCourse: false,
                showM1Course: false,
                showJob: false,
            },
            {
                title: "Start applying for work!",
                text: "You can specialize in areas such as penetration testing, network security, or cryptography based on your interests and career goals.",
                icon: "briefcase",
                showCourse: false,
                showM1Course: false,
                showJob: true,
            },
        ],
    },
    {
        title: "Product/Project Manager",
        slug: "pm",
        paraTitle: "product manager",
        featured: false,
        ...dummyData,
    },
    {
        title: "UI/UX Designer",
        slug: "uiux",
        paraTitle: "UI/UX designer",
        featured: true,
        description:
            "UI/UX designers enhance user satisfaction by improving the usability, accessibility, and pleasure provided in the interaction between the user and the product. This role is pivotal as businesses increasingly prioritize user experience to differentiate themselves in crowded markets.",
        do: [
            "Conduct user research and interviews",
            "Create user personas and journey maps",
            "Design wireframes, mockups, and prototypes",
            "Test designs and gather feedback",
            "Collaborate with developers and product managers",
        ],
        skills: [
            {
                title: "Creative thinking",
                slug: "creative",
            },
            {
                title: "User empathy",
                slug: "teamwork",
            },
            {
                title: "Attention to detail",
                slug: "detail",
            },
            {
                title: "Communication skills",
                slug: "comm",
            },
            {
                title: "Problem-solving ability",
                slug: "problem",
            },
        ],
        how: [
            {
                title: "Gain academic qualification or certificates",
                text: "Earn a certificate or degree in design, human-computer interaction, or a related field to build a strong foundational knowledge.",
                icon: "certificate",
                showCourse: true,
                showM1Course: false,
                showJob: false,
            },
            {
                title: "Keep your skills updated",
                text: "Stay updated with the latest design tools and trends by attending workshops, courses, and following industry leaders.",
                icon: "skills",
                showCourse: false,
                showM1Course: true,
                showJob: false,
            },
            {
                title: "Create projects and grow your portfolio",
                text: "Develop a solid portfolio showcasing a range of design projects that highlight your skills and design thinking.",
                icon: "file",
                showCourse: false,
                showM1Course: false,
                showJob: false,
            },
            {
                title: "Explore internship opportunities",
                text: "Participate in internships or freelance projects to gain practical experience and learn from established designers.",
                icon: "building",
                showCourse: false,
                showM1Course: false,
                showJob: false,
            },
            {
                title: "Start applying for work!",
                text: "Begin your professional journey by applying for roles that align with your skills and aspirations.",
                icon: "briefcase",
                showCourse: false,
                showM1Course: false,
                showJob: true,
            },
        ],
    },
    {
        title: "Business & Management",
        slug: "business",
        paraTitle: "business manager",
        featured: true,
        description:
            "Professionals in Business Analytics and Tech Management harness data to drive strategic decisions and manage technology within organizations. This dual role is crucial as it blends analytical rigor with technical oversight to optimize business performance and technological innovation.",
        do: [
            "Analyze complex data sets to inform strategic decisions",
            "Manage technology projects and ensure alignment with business goals",
            "Develop and implement data governance and management policies",
            "Lead cross-functional teams to deliver technology solutions",
            "Evaluate new technologies to enhance business processes",
        ],
        skills: [
            {
                title: "Strategic thinking",
                slug: "problem",
            },
            {
                title: "Leadership capabilities",
                slug: "teamwork",
            },
            {
                title: "Analytical proficiency",
                slug: "learn",
            },
            {
                title: "Tech-savvy",
                slug: "calc",
            },
            {
                title: "Effective communication",
                slug: "comm",
            },
        ],
        how: [
            {
                title: "Gain academic qualification or certificates",
                text: "Obtain a certificate or degree in business analytics, information systems, or a related field to gain essential knowledge.",
                icon: "certificate",
                showCourse: true,
                showM1Course: false,
                showJob: false,
            },
            {
                title: "Learn a language, framework or tech stack",
                text: "Enhance your skills in project management and analytics tools to enhance your skills and credibility.",
                icon: "skills",
                showCourse: false,
                showM1Course: true,
                showJob: false,
            },
            {
                title: "Explore internship opportunities",
                text: "Gain hands-on experience and valuable insights through targeted internship programmes.",
                icon: "building",
                showCourse: false,
                showM1Course: false,
                showJob: false,
            },
            {
                title: "Start applying for work!",
                text: "Begin your professional journey by applying for roles that align with your skills and aspirations.",
                icon: "briefcase",
                showCourse: false,
                showM1Course: false,
                showJob: true,
            },
        ],
    },
    {
        title: "Financial Technology",
        slug: "fintech",
        paraTitle: "fintech engineer",
        featured: true,
        description:
            "Fintech professionals combine expertise in finance and technology to innovate and streamline financial services. This career is at the forefront of financial evolution, playing a pivotal role in transforming traditional financial sectors through technology.",
        do: [
            "Develop new financial technologies and solutions",
            "Analyze financial data to drive product development",
            "Implement and manage digital financial platforms",
            "Collaborate with engineers and product managers to enhance fintech services",
            "Stay updated with regulatory changes and ensure compliance",
        ],
        skills: [
            {
                title: "Strong analytical skills",
                slug: "problem",
            },
            {
                title: "Knowledge of financial markets",
                slug: "chart",
            },
            {
                title: "Tech proficiency",
                slug: "calc",
            },
            {
                title: "Innovative thinking",
                slug: "learn",
            },
            {
                title: "Risk management",
                slug: "time",
            },
        ],
        how: [
            {
                title: "Gain academic qualification or certificates",
                text: "Earn a certificate or bachelor's degree in finance, computer science, or a related field to build foundational knowledge.",
                icon: "certificate",
                showCourse: true,
                showM1Course: false,
                showJob: false,
            },
            {
                title: "Enhance your statistical and programming skills",
                text: "Build a strong foundation in your chosen programming languages or technology stacks. ",
                icon: "skills",
                showCourse: false,
                showM1Course: true,
                showJob: false,
            },
            {
                title: "Explore internship opportunities",
                text: "Gain experience with internships or jobs in banking, software development, or financial analysis to understand the financial and tech sectors.",
                icon: "building",
                showCourse: false,
                showM1Course: false,
                showJob: false,
            },
            {
                title: "Start applying for work!",
                text: "Begin your professional journey by applying for roles that align with your skills and aspirations.",
                icon: "briefcase",
                showCourse: false,
                showM1Course: false,
                showJob: true,
            },
        ],
    },
];
