const roles = [
    "Software engineer",
    "Data science",
    "UI/UX designer",
    "Product/Project manager",
    "Business & management",
    "Digital marketing",
    "Cybersecurity",
    "Sales & accounts",
    "Consulting & systems integration",
    "IT Support",
    "Network & system administration",
    "Graphics design",
    "Multimedia",
    "Technical writing",
    "Other",
];
